name: Upload Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  markdown_to_confluence_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: ./ # Uses an action in the root directory
        id: Convert
        with:
          fileslocation: 'documentation'
          should_upload: true
          confluence_url: 'https://at-bachelor.atlassian.net'
          confluence_space_key: '~955037829'
          auth_username: ${{ secrets.AUTH_USERNAME }}
          auth_api_token: ${{ secrets.AUTH_API_TOKEN }}