name: Upload Documentation

# on:
#   pull_request:
#     branches:
#       - main

on: [push]


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        env:
          CONFLUENCE_URL: 'https://at-bachelor.atlassian.net'
          CONFLUENCE_SPACE_KEY: '~955037829'
          #AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          AUTH_TOKEN: 'bGFyc2UxOUBzdHVkZW50LnNkdS5kazpoYVpaSEM5MTFZc0ZUb2pXODV3WTk3Nzg='
        uses: ./ # Uses an action in the root directory
        id: Convert
        with:
          fileslocation: './documentation'
