name: Upload Documentation

on: [pull-request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        env:
          CONFLUENCE_URL: 'https://at-bachelor.atlassian.net/wiki'
          CONFLUENCE_SPACE_KEY: '~955037829'
          #AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          AUTH_TOKEN: 'bGFyc2UxOUBzdHVkZW50LnNkdS5kazp6RzFrQk1ick9PUEtZblNSSFA0bTQxNUI='
        uses: ./ # Uses an action in the root directory
        id: Convert
        with:
          fileslocation: './documentation'
