on: [push]
jobs:
  markdown_to_confluence_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: KejiaWang3/MarkdownToConfluence
        with:
          fileslocation: './documentation'
          should_upload: true
          confluence_url: 'https://dpdd.atlassian.net'
          confluence_space_key: '~63b85c94082abdd71bb77ba3'
          auth_username: ${{ secrets.AUTH_USERNAME }}
          auth_api_token: ${{ secrets.AUTH_API_TOKEN }}
          is_preview: false
