jobs:
  markdown_to_confluence_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: TTengs/MarkdownToConfluence@v3
        with:
          fileslocation: './documentation'
          should_upload: true
          confluence_url: 'https://network.atlassian.net/wiki'
          confluence_space_key: '~63b85c94082abdd71bb77ba3
          auth_username: ${{ kejia.wang@gov.bc.ca }}
          auth_api_token: ${{ ATATT3xFfGF0Y9mGsKc2-RJUfwQPwZ7afjMBYJzNHFBU0UJWR25-PpxW3TzSbNO4z6XrbtdVjX3AcZrUwEG0iHOrFp9kDGBCVA9zl5PCnWmztr5F6w_riINyvwoXHUrMANHjf3d4s3QFcShwmNlZQl6iCQTUtfHRTCyRb8zE7-mdCi7hyCZbMgY=CFEE3F51 }}
          is_preview: false
